name: Code Checker

on:
  push:
    paths:
      - "**.py"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Format the code with yapf
      run: |
        yapf $(git ls-files '*.py')
    - name: action metadata
      run: |
        echo -e "action     : ${{ github.action }}"
        echo -e "actor      : ${{ github.actor }}"
        echo -e "event_name : ${{ github.event_name }}"
        echo -e "job        : ${{ github.job }}"
        echo -e "ref        : ${{ github.ref }}"
        echo -e "repository : ${{ github.repository }}"
        echo -e "run_id     : ${{ github.run_id }}"
        echo -e "sha        : ${{ github.sha }}"
        echo -e "workflow   : ${{ github.workflow }}"
        echo -e "workspace  : ${{ github.workspace }}"
    - name: config github
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: add changes
      run: |
        git add .
    - name: commit changes
      run: |
        git commit -m "Automation: Formatter" --all | exit 0
    - name: push changes
      if: github.ref == 'refs/heads/main'
      run: |
        git push
